/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javabasics;

import java.util.Random;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int n){

        int[] rollResult = new int[n];

        for (int i = 0; i < n; i++) {

            Random generator = new Random();
            Float randomNumber = generator.nextFloat();

            //This feels like the wrong way to get a number between 1 and 6, but it works, so...
            int randomDice = Math.round(randomNumber * 5) + 1;

            rollResult[i] = randomDice;
        }
        return rollResult;
    }

    public boolean containsDuplicates(String[] arrayToCheck) {
        boolean hasDups = false;
        dupCheck:

            for (int i = 0; i < arrayToCheck.length; i++){
                for (int j = 0; j < arrayToCheck.length; j++) {
                    if ((arrayToCheck[i].equals(arrayToCheck[j])) && (i != j)) {
                        hasDups = true;
                        break dupCheck;
                    }
                }
            }
            return hasDups;
    }

    public int calculateAverage(int[] arrayToAverage){

        if (arrayToAverage.length == 1) {
            return arrayToAverage.length;
        }

        int sum = 0;

        for (int number : arrayToAverage) {
            sum = sum + number;
        }

        return sum/arrayToAverage.length;
    }

    public int[] lowestAverageArray(int[][] arrayOfArrays){

        int winningAvg = 0;
        int winningIndex = 0;
        int counter = 0;

        for (int[] singleArray:  arrayOfArrays) {

            if (winningAvg == 0) {
                winningAvg = calculateAverage(singleArray);
            }
            int currentAvg = calculateAverage(singleArray);
            if (currentAvg <= winningAvg) {
                winningAvg = currentAvg;
                winningIndex = counter;
            }
            counter++;
        }
        return arrayOfArrays[winningIndex];
    }

}
