/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String checkForSemicolon(String filePath){

        System.out.println(filePath);
        String result = "Linter Results: \n";
        try {
            Scanner fileContents = new Scanner(new File(filePath));
            int lineNum = 0;

            boolean anyErrors = false;
            while (fileContents.hasNextLine()){
                lineNum++;
                String line = fileContents.nextLine();
                if (line.length() > 0) {
                    String lastChar = line.substring(line.length() - 1);
                    if (!lastChar.equals(";") && !lastChar.equals("{") && !lastChar.equals("}") && !line.contains("if") && !line.contains("else")){
                        result = result + "Line " + lineNum + ": Missing semicolon.\n";
                        anyErrors = true;
                    }
                }
            }

            if (!anyErrors) {
                result = "No errors.";
            }

            System.out.println(result);

        } catch (FileNotFoundException exception) {
            System.out.println(exception);
        }

        return result;
    }

    public static void main(String[] args) {

        String path = "src/main/resources/gates.js";

        System.out.println(new App().checkForSemicolon(path));

    }
}
