/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testRestaurantChain() {
        Restaurant restaurant = new Restaurant("The Knife and Cleaver", "$$$", "Charlie Wells");
        User user = new User("Giles Coren");
        RestaurantReview restaurantReview = new RestaurantReview(user, "Food tastes of despair.", 4, restaurant);
        restaurant.addReview(restaurantReview);
        assertEquals("The restaurant The Knife and Cleaver has 4 stars, and is rated $$$ for price. The Knife and Cleaver is part of the Charlie Wells chain.", restaurant.toString());
    }

    @Test public void testSingleRestaurant() {
        Restaurant restaurant = new Restaurant("The Knife and Cleaver", "$$$");
        User user = new User("Giles Coren");
        RestaurantReview restaurantReview = new RestaurantReview(user, "Food tastes of despair.", 4, restaurant);
        restaurant.addReview(restaurantReview);
        assertEquals("The restaurant The Knife and Cleaver has 4 stars, and is rated $$$ for price.",restaurant.toString());
    }

    @Test public void testAverageStars(){
        Restaurant restaurant = new Restaurant("The Knife and Cleaver", "$$$");
        User userOne = new User("Giles Coren");
        User userTwo = new User("Hugo Rifkind");
        RestaurantReview restaurantReviewOne = new RestaurantReview(userOne, "Food tastes of despair.", 4, restaurant);
        RestaurantReview restaurantReviewTwo = new RestaurantReview(userTwo, "Food tastes of enthusiasm.", 2, restaurant);
        restaurant.addReview(restaurantReviewOne);
        restaurant.addReview(restaurantReviewTwo);
        //(2+4)/2 = 3 stars expected.
        assertEquals("The restaurant The Knife and Cleaver has 3 stars, and is rated $$$ for price.",restaurant.toString());
    }


}
