/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testRestaurant() {
        Restaurant restaurant = new Restaurant("The Knife and Cleaver", 4);
        assertEquals("Restaurant The Knife and Cleaver has 4 stars.", restaurant.toString());
    }
}
