/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class ReviewTest {
    @Test public void testReview() {
        Review review = new Review("Giles Coren", "Food tastes of despair.", 4);
        assertEquals("Giles Coren says: Food tastes of despair. Rating: 4 stars.", review.toString());
    }
}
